GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc0LCJuYW1lIjoicmVuZGkiLCJlbWFpbCI6InJlbmRpQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQ2OTAxNzY1LCJleHAiOjE3NDY5MDE3ODV9.x4PrX0OmS6HyMUWgJLibafVJ-xYxoo-yDroQt18cP3U
###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "admin123",
  "email": "admin@gmail.com",
  "password": "12345678",
  "confPassword": "12345678"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
  
  "email": "admin@gmail.com",
  "password": "12345678"

}


###
GET http://localhost:5000/token




###
DELETE  http://localhost:5000/logout